name: ðŸš€ Deploy Website on Push
on:
  push:
    branches: [ master ]
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get Latest Code
      uses: actions/checkout@v4
    - name: ðŸ“‚ Sync Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER3 }}
        username: ${{ secrets.FTP_USERNAME3 }}
        password: ${{ secrets.FTP_PASSWORD3 }}
        server-dir: htdocs/  # Adjust to your target directory, e.g., public_html/subfolder/
        protocol: ftp  # Use 'ftps' for secure FTP if supported by Namecheap
        port: 21  # Adjust to 21098 for SFTP if needed
